spring.application.name=work-schedule-service
server.port=${SERVER_PORT_WORK} 
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.schemas=work-schedule
spring.flyway.default-schema=work-schedule
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration

department.service.url=${DEPARTMENT_SERVICE_URL}
employee.service.url=${EMPLOYEE_SERVICE_URL}