spring.application.name=support-service

server.port=${SERVER_PORT_SUPPORT}

# DATABASE
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY
spring.flyway.enabled=true
spring.flyway.schemas=support
spring.flyway.default-schema=support
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=${JWT_SECRET}

auth.service.url=${AUTH_SERVICE_URL}