export const POSITION_OPTIONS_TR = [
    "İK Müdürü",
    "İK Uzmanı",
    "İşe Alım Uzmanı",
    "Yetenek Kazanımı Uzmanı",
    "İK Asistanı",
    "Finans Müdürü",
    "Finansal Analist",
    "Bütçe Uzmanı",
    "Hazine Uzmanı",
    "Muhasebeci",
    "Kıdemli Muhasebeci",
    "Bordro Uzmanı",
    "Vergi Uzmanı",
    "Satış Müdürü",
    "Satış Temsilcisi",
    "Müşteri Yöneticisi",
    "Stratejik Müşteri Yöneticisi",
    "Pazarlama Müdürü",
    "Dijital Pazarlama Uzmanı",
    "Sosyal Medya Yöneticisi",
    "İçerik Üreticisi",
    "SEO Uzmanı",
    "BT Müdürü",
    "Sistem Yöneticisi",
    "Ağ Mühendisi",
    "Siber Güvenlik Uzmanı",
    "BT Destek Uzmanı",
    "Operasyon Müdürü",
    "Operasyon Uzmanı",
    "Süreç Analisti",
    "Saha Operasyon Personeli",
    "Müşteri Destek Uzmanı",
    "Çağrı Merkezi Temsilcisi",
    "Müşteri Başarı Yöneticisi",
    "Teknik Destek Uzmanı",
    "Hukuk Danışmanı",
    "Avukat",
    "Uyum Uzmanı",
    "Sözleşme Uzmanı",
    "Tedarik Müdürü",
    "Satın Alma Uzmanı",
    "Tedarikçi Yöneticisi",
    "Kaynak Bulma Uzmanı",
    "Lojistik Müdürü",
    "Tedarik Zinciri Uzmanı",
    "Depo Yöneticisi",
    "Dağıtım Koordinatörü",
    "AR-GE Mühendisi",
    "Araştırma Bilimcisi",
    "İnovasyon Uzmanı",
    "Ürün Geliştirme Mühendisi",
    "Ürün Müdürü",
    "Ürün Sahibi",
    "Ürün Analisti",
    "UX Araştırmacısı",
    "Kalite Güvence Uzmanı",
    "Kalite Mühendisi",
    "Kalite Müdürü",
    "Denetim Uzmanı",
    "Eğitim Uzmanı",
    "Öğrenme ve Gelişim Müdürü",
    "Öğretim Tasarımcısı",
] as const;
